"""The reframe decision file — ``reframe.def`` (INI-091 Phase 3).

The reframe-decision file *is the deliverable*; the reframed clip is a regenerable
render of it. It mirrors the rough-cut (``roughcut.def``) and overlay (``overlay.def``)
decision-file pattern exactly: a human-editable YAML document that Propose writes and
Render consumes, round-tripping losslessly.

What it carries
---------------
  - **target** — the project Target reference: ``aspect`` (preset key) + ``resolution``
    (``"auto"`` or a tier). The crop *shape* and output *size*.
  - **mode** — ``static`` | ``dynamic``. (Dynamic *locks* are Phase 5; the field is
    carried now so the artifact is forward-stable.)
  - **lock** — the dynamic composition-lock axis (``none`` | ``x`` | ``y`` | ``both``),
    carried for Phase 5; unused by the static geometry.
  - **framing model** — ``scale`` / ``pan_x`` / ``pan_y``: the canonical crop
    description (:mod:`video_pipeline.reframe.model`). Render resolves *exactly* this to
    the pixel crop — no re-derivation.
  - **framing_intent** — the named preset the model started from (e.g. ``performer``),
    advisory once edited.
  - **custom** — ``True`` once the framing has been hand-edited off its preset. Editing
    detaches the preset to "Custom"; resetting re-attaches it (see :meth:`detach` /
    :meth:`reset_to_proposal`).
  - **safe_zone_mode** — the normalized safe-zone mode (``none`` | ``generic`` |
    ``custom``) the reframe was composed against.
  - **subject_track** — the path to the persisted subject track (``track_io``), so
    Render replays the geometry without re-running the native tracker.

Editing detaches to Custom
--------------------------
The framing model is the proposal's initial value. A hand-edit to ``scale`` / ``pan_x``
/ ``pan_y`` is a deliberate override, so :meth:`detach` flips ``custom`` True (the GUI's
"Custom" framing badge). :meth:`reset_to_proposal` restores the original ML proposal and
clears ``custom`` — the "reset to proposal" affordance the box and knobs expose.

Example (abridged)::

    source: 2026-06-03-reel.mp4
    target: {aspect: full-portrait, resolution: auto}
    mode: static
    lock: none
    framing_intent: performer
    custom: false
    safe_zone_mode: generic
    subject_track: work/2026-06-03-reel.track.json
    framing: {scale: 1.0, pan_x: 0.42, pan_y: 0.35}
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import yaml

from ..safezone.normalized import DEFAULT_MODE as DEFAULT_SAFE_ZONE_MODE
from ..safezone.normalized import SAFE_ZONE_MODES
from ..target_format import DEFAULT_ASPECT, RESOLUTION_SELECTIONS, Target, aspect_preset
from .framing import DEFAULT_FRAMING
from .model import FramingModel

# Reframe modes (static crop vs dynamic follow). Dynamic locks land in Phase 5.
MODES = ("static", "dynamic")
DEFAULT_REFRAME_MODE = "static"

# Composition-lock axes, carried for Phase 5 (dynamic). "none" = no lock.
LOCKS = ("none", "x", "y", "both")
DEFAULT_LOCK = "none"

REFRAME_DEF_VERSION = "1.0"


def _round(v: float) -> float:
    return round(float(v), 6)


_HEADER = (
    "# reframe file — generated by video_pipeline.reframe (INI-091 Phase 3).\n"
    "# THIS FILE IS THE PRODUCT. The reframed clip is a regenerable render of it.\n"
    "# Render resolves `framing` {scale, pan_x, pan_y} to the EXACT pixel crop — the\n"
    "# geometry here is the geometry rendered, no re-derivation. Edit the framing by\n"
    "# nudging scale (punch-in; 1.0 = widest native crop) or pan_x/pan_y (crop CENTRE\n"
    "# in normalized source coords 0-1), then re-render. Hand-editing the framing\n"
    "# detaches the preset to Custom. `subject_track` references the persisted track\n"
    "# so Render needs no re-tracking. source/ is never modified.\n"
)


@dataclass
class ReframeDef:
    """The reframe-decision document over a single source clip.

    The framing model (``scale`` / ``pan_x`` / ``pan_y``) is the canonical crop; the
    rest is target/mode/safe-zone context + the subject-track reference. ``proposal``
    retains the original ML proposal so :meth:`reset_to_proposal` can restore it.
    """

    source: str
    target: Target = field(default_factory=Target)
    framing: FramingModel = field(default_factory=FramingModel)
    mode: str = DEFAULT_REFRAME_MODE
    lock: str = DEFAULT_LOCK
    framing_intent: Optional[str] = DEFAULT_FRAMING
    custom: bool = False
    safe_zone_mode: str = DEFAULT_SAFE_ZONE_MODE
    subject_track: Optional[str] = None
    # The original ML proposal (for reset-to-proposal); defaults to the initial framing.
    proposal: Optional[FramingModel] = None
    duration: Optional[float] = None

    def __post_init__(self) -> None:
        if self.mode not in MODES:
            raise ValueError(f"mode {self.mode!r} not in {MODES}")
        if self.lock not in LOCKS:
            raise ValueError(f"lock {self.lock!r} not in {LOCKS}")
        if self.safe_zone_mode not in SAFE_ZONE_MODES:
            raise ValueError(
                f"safe_zone_mode {self.safe_zone_mode!r} not in {SAFE_ZONE_MODES}"
            )
        # target/resolution validity is enforced by the Target value object itself.
        if self.target.resolution not in RESOLUTION_SELECTIONS:
            raise ValueError(f"invalid resolution {self.target.resolution!r}")
        aspect_preset(self.target.aspect)
        if self.proposal is None:
            self.proposal = self.framing

    # ── editing semantics ──────────────────────────────────────────────────────────

    def detach(self, framing: FramingModel) -> "ReframeDef":
        """Apply a hand-edited framing, detaching the preset to Custom.

        The proposal is preserved so :meth:`reset_to_proposal` can restore it. Returns
        ``self`` for chaining (mutates in place — the def is the live document).
        """
        self.framing = framing
        self.custom = True
        return self

    def reset_to_proposal(self) -> "ReframeDef":
        """Restore the original ML proposal and re-attach the preset (clear Custom)."""
        self.framing = self.proposal if self.proposal is not None else FramingModel()
        self.custom = False
        return self

    # ── serialization ──────────────────────────────────────────────────────────────

    def to_dict(self) -> dict:
        return {
            "source": self.source,
            "version": REFRAME_DEF_VERSION,
            "target": {"aspect": self.target.aspect, "resolution": self.target.resolution},
            "mode": self.mode,
            "lock": self.lock,
            "framing_intent": self.framing_intent,
            "custom": self.custom,
            "safe_zone_mode": self.safe_zone_mode,
            "subject_track": self.subject_track,
            "duration": (_round(self.duration) if self.duration is not None else None),
            "framing": self.framing.to_dict(),
            "proposal": (self.proposal.to_dict() if self.proposal is not None else None),
        }

    def to_yaml(self) -> str:
        d = self.to_dict()
        # Head fields render block-style; the two model rows render inline (flow) so a
        # knob nudge is a single, legible one-line edit — same shape as overlay rows.
        head = {k: d[k] for k in (
            "source", "version", "mode", "lock", "framing_intent", "custom",
            "safe_zone_mode", "subject_track", "duration",
        )}
        head_yaml = yaml.safe_dump(
            head, sort_keys=False, allow_unicode=True, default_flow_style=False
        )
        target_row = yaml.safe_dump(
            d["target"], sort_keys=False, default_flow_style=True, width=10_000
        ).strip()
        framing_row = yaml.safe_dump(
            d["framing"], sort_keys=False, default_flow_style=True, width=10_000
        ).strip()
        proposal_row = (
            yaml.safe_dump(d["proposal"], sort_keys=False, default_flow_style=True,
                           width=10_000).strip()
            if d["proposal"] is not None else "null"
        )
        body = (
            f"target: {target_row}\n"
            f"framing: {framing_row}\n"
            f"proposal: {proposal_row}\n"
        )
        return _HEADER + head_yaml + body

    @classmethod
    def from_dict(cls, d: dict) -> "ReframeDef":
        t = d.get("target") or {}
        target = Target(
            aspect=str(t.get("aspect", DEFAULT_ASPECT)),
            resolution=str(t.get("resolution", "auto")),
        )
        proposal = (
            FramingModel.from_dict(d["proposal"])
            if d.get("proposal") is not None else None
        )
        return cls(
            source=str(d.get("source", "")),
            target=target,
            framing=FramingModel.from_dict(d.get("framing") or {}),
            mode=str(d.get("mode", DEFAULT_REFRAME_MODE)),
            lock=str(d.get("lock", DEFAULT_LOCK)),
            framing_intent=d.get("framing_intent"),
            custom=bool(d.get("custom", False)),
            safe_zone_mode=str(d.get("safe_zone_mode", DEFAULT_SAFE_ZONE_MODE)),
            subject_track=d.get("subject_track"),
            proposal=proposal,
            duration=(float(d["duration"]) if d.get("duration") is not None else None),
        )

    @classmethod
    def from_yaml(cls, text: str) -> "ReframeDef":
        data = yaml.safe_load(text) or {}
        if not isinstance(data, dict):
            raise ValueError("reframe file did not parse to a mapping")
        return cls.from_dict(data)

    def write(self, path) -> None:
        Path(path).write_text(self.to_yaml(), encoding="utf-8")

    @classmethod
    def read(cls, path) -> "ReframeDef":
        return cls.from_yaml(Path(path).read_text(encoding="utf-8"))
