"""The caption file — the product of the captions phase.

Mirrors the rough-cut decision file: the **editable caption file is the
deliverable**; the rendered caption overlay (Remotion) is a regenerable view of
it. It is human-editable YAML — a flat, ordered list of cues, each a short
on-screen caption with its own start/end timing.

To fix a caption the CEO edits ``text:`` (or nudges ``start`` / ``end``, or
flips ``keep:``) and re-renders. The edit round-trips: :meth:`CaptionTrack.
from_yaml` parses exactly what :meth:`CaptionTrack.to_yaml` writes, so a
hand-edited file loads back losslessly. The pipeline never modifies ``source/``.

``emphasis`` carries the indices (within the cue's ``words``) that the style
layer should accent — glossary canonical terms by default. It is advisory: the
Remotion renderer reads it; editing it changes only the look.

Example (abridged)::

    source: 2026-06-03-reel.mp4
    identity: dyson-hope
    profile: reels-9x16
    style_ref: caption-styles/dyson-hope
    cues:
      - {i: 0, start: 0.400, end: 1.120, keep: true, text: "I used to",      emphasis: []}
      - {i: 1, start: 1.120, end: 2.040, keep: true, text: "make fun of",    emphasis: []}
      - {i: 2, start: 2.040, end: 2.880, keep: true, text: "SIGIL.ZERO",     emphasis: [0]}
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional

import yaml


def _round(t: float) -> float:
    return round(float(t), 3)


@dataclass
class Cue:
    """One on-screen caption spanning ``[start, end)`` of the source clip.

    ``words`` is the cue's tokens in order; ``text`` is their join (the human-
    editable surface). ``emphasis`` indexes into ``words`` for accented tokens.
    ``keep`` False suppresses the cue from the render without deleting it from
    the file (so the CEO can toggle it back).
    """

    index: int
    start: float
    end: float
    words: List[str] = field(default_factory=list)
    emphasis: List[int] = field(default_factory=list)
    keep: bool = True

    def __post_init__(self):
        self.start = _round(self.start)
        self.end = _round(self.end)
        self.words = [str(w) for w in self.words]
        self.emphasis = sorted({int(i) for i in self.emphasis if 0 <= int(i) < len(self.words)})

    @property
    def text(self) -> str:
        return " ".join(self.words).strip()

    @property
    def duration(self) -> float:
        return _round(max(0.0, self.end - self.start))

    def emphasis_words(self) -> List[str]:
        return [self.words[i] for i in self.emphasis]

    def to_dict(self) -> dict:
        # compact, key-ordered mapping (renders inline as flow style). ``text`` is
        # the editable surface; ``words`` is reconstructed from it on read so a
        # hand-edit of ``text`` is honoured without the editor touching ``words``.
        return {
            "i": self.index,
            "start": self.start,
            "end": self.end,
            "keep": self.keep,
            "text": self.text,
            "emphasis": list(self.emphasis),
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Cue":
        # ``words`` derives from ``text`` (the editable surface) unless an explicit
        # ``words`` list is present (round-trip of a machine-written file).
        if d.get("words"):
            words = [str(w) for w in d["words"]]
        else:
            words = str(d.get("text", "") or "").split()
        return cls(
            index=int(d.get("i", d.get("index", 0))),
            start=float(d["start"]),
            end=float(d["end"]),
            words=words,
            emphasis=[int(i) for i in (d.get("emphasis") or [])],
            keep=bool(d.get("keep", True)),
        )


_HEADER = (
    "# caption file — generated by video_pipeline.captions (INI-085 Phase 3).\n"
    "# THIS FILE IS THE PRODUCT. The caption overlay is a regenerable render of it.\n"
    "# Fix a caption by editing `text:` (or nudging start/end, or flipping `keep:`),\n"
    "# then re-render:  video-pipeline captions-render <this-file> -o <out.mov>\n"
    "# `emphasis` indexes the words the style layer accents. source/ is never touched.\n"
)


@dataclass
class CaptionTrack:
    """An ordered caption document over a single source clip."""

    source: str
    cues: List[Cue] = field(default_factory=list)
    identity: Optional[str] = None
    profile: Optional[str] = None
    style_ref: Optional[str] = None
    language: Optional[str] = None

    # ── views ──
    def kept(self) -> List[Cue]:
        return [c for c in self.cues if c.keep]

    def reindex(self) -> "CaptionTrack":
        """Renumber cues 0..n-1 in time order (after a hand edit)."""
        self.cues.sort(key=lambda c: (c.start, c.end))
        for i, c in enumerate(self.cues):
            c.index = i
        return self

    # ── serialization ──
    def to_yaml(self) -> str:
        head = {
            "source": self.source,
            "identity": self.identity,
            "profile": self.profile,
            "style_ref": self.style_ref,
            "language": self.language,
            "cue_count": len(self.cues),
        }
        head_yaml = yaml.safe_dump(
            head, sort_keys=False, allow_unicode=True, default_flow_style=False
        )
        lines = ["cues:"]
        for c in self.cues:
            row = yaml.safe_dump(
                c.to_dict(), sort_keys=False, allow_unicode=True,
                default_flow_style=True, width=10_000,
            ).strip()
            lines.append(f"  - {row}")
        return _HEADER + head_yaml + "\n".join(lines) + "\n"

    @classmethod
    def from_yaml(cls, text: str) -> "CaptionTrack":
        data = yaml.safe_load(text) or {}
        if not isinstance(data, dict):
            raise ValueError("caption file did not parse to a mapping")
        cues = [Cue.from_dict(d) for d in (data.get("cues") or [])]
        return cls(
            source=str(data.get("source", "")),
            cues=cues,
            identity=data.get("identity"),
            profile=data.get("profile"),
            style_ref=data.get("style_ref"),
            language=data.get("language"),
        )

    def write(self, path) -> None:
        from pathlib import Path

        Path(path).write_text(self.to_yaml(), encoding="utf-8")

    @classmethod
    def read(cls, path) -> "CaptionTrack":
        from pathlib import Path

        return cls.from_yaml(Path(path).read_text(encoding="utf-8"))
